### ISSUE TITLE
Error on Packaging

### ISSUE THREAD

**Issue by Angelo-Gebauer** [microsoft/MixedRealityToolkit-Unreal#10] opened 2020-11-13 09:08 UTC
## UX Tools for Unreal v0.10.0

> **UATHelper: Packaging (HoloLens):   LogPython: Error: '/Script/UXTools.EUxtPaginateResult' has an invalid 'ScriptName' meta-data value 'Failed, Concurrent Operation': Name contains ',' which is invalid for Python.**

> **UATHelper: Packaging (HoloLens):   LogPython: Error: '/Script/UXTools.EUxtPaginateResult' has an invalid 'ScriptName' meta-data value 'Failed, Concurrent User Interaction': Name contains ',' which is invalid for Python.**

> **UATHelper: Packaging (HoloLens):   LogPython: Error: '/Script/UXTools.EUxtScrollDirection' has an invalid 'ScriptName' meta-data value 'Up And Down': Name contains ' ' which is invalid for Python.**

> **UATHelper: Packaging (HoloLens):   LogPython: Error: '/Script/UXTools.EUxtScrollDirection' has an invalid 'ScriptName' meta-data value 'Left And Right': Name contains ' ' which is invalid for Python.**

> **PackagingResults: Error: '/Script/UXTools.EUxtPaginateResult' has an invalid 'ScriptName' meta-data value 'Failed, Concurrent Operation': Name contains ',' which is invalid for Python.**

> **PackagingResults: Error: '/Script/UXTools.EUxtPaginateResult' has an invalid 'ScriptName' meta-data value 'Failed, Concurrent User Interaction': Name contains ',' which is invalid for Python.**

> **PackagingResults: Error: '/Script/UXTools.EUxtScrollDirection' has an invalid 'ScriptName' meta-data value 'Up And Down': Name contains ' ' which is invalid for Python.**

> **PackagingResults: Error: '/Script/UXTools.EUxtScrollDirection' has an invalid 'ScriptName' meta-data value 'Left And Right': Name contains ' ' which is invalid for Python.**

**Comment by luis-valverde-ms** [comment] 2021-01-19 15:01
Closing this as a duplicate of https://github.com/microsoft/MixedReality-UXTools-Unreal/issues/16

**Closed by luis-valverde-ms** 2021-01-19 15:01 UTC
